"""Pydantic models for the Planner/Thinker (S4).

Defines all data structures used in the NL → Spec pipeline:
- LanguageGame: domain classification
- Ambiguity: ambiguous term with possible meanings
- ClarifyingQuestion: user-facing disambiguation
- ArchitectureTemplate: predefined architectural paths
- BuildSpec: the structured output for the Coding Agent
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone
from enum import Enum
from typing import Annotated, Any, Literal

from pydantic import BaseModel, Field, field_serializer


# ── Language Game (Wittgenstein) ──────────────────────────────────────────


class LanguageGame(str, Enum):
    """Domain-specific language game. Each game has its own terminology rules."""

    SOFTWARE_ENGINEERING = "software_engineering"
    SYSTEMS_ARCHITECTURE = "systems_architecture"
    BUDDHIST_PHILOSOPHY = "buddhist_philosophy"
    GENERAL = "general"


# ── Ambiguity ─────────────────────────────────────────────────────────────


class Ambiguity(BaseModel):
    """An ambiguous term in the user's prompt with possible meanings."""

    term: str
    possible_meanings: list[str] = Field(
        ..., min_length=1, description="All possible interpretations of this term"
    )
    criticality: Literal["critical", "moderate", "minor"] = "minor"
    domain: LanguageGame | None = None

    @field_serializer("criticality")
    def _serialize_criticality(self, v: str) -> str:
        return v


class AmbiguityResolution(str, Enum):
    """How an ambiguity was resolved."""

    ASK_USER = "ask_user"
    OPTIMAL_CHOICE = "optimal_choice"
    IGNORED = "ignored"


# ── Clarifying Question ──────────────────────────────────────────────────


class ClarifyingQuestion(BaseModel):
    """A question posed to the user to resolve ambiguity."""

    question: str
    options: list[str]
    default: str = Field(..., description="Optimal default if user says 'decide for me'")
    reason: str = Field(
        ..., description="Why this question is being asked"
    )


# ── Architecture Template ────────────────────────────────────────────────


class ArchitectureTemplate(BaseModel):
    """A predefined architectural path the user can choose from."""

    name: str
    description: str
    pros: list[str]
    cons: list[str]
    use_cases: list[str]
    recommended_for: str = Field(
        ..., description="Brief description of when this template is recommended"
    )

    def score(self, requirements: list[str]) -> float:
        """Score how well this template fits the given requirements.

        Simple heuristic: count keyword matches between requirements and template fields.
        """
        req_text = " ".join(requirements).lower()
        score = 0.0

        if any(kw in req_text for kw in ["small", "simple", "quick", "prototype", "MVP"]):
            score += 0.5
        if any(kw in req_text for kw in ["large", "complex", "enterprise", "scale", "team"]):
            score += 0.5
        if any(kw in req_text for kw in ["feature", "module", "component"]):
            score += 0.3
        if any(kw in req_text for kw in ["layer", "tier", "separation"]):
            score += 0.3

        return score


class ArchitectureChoice(BaseModel):
    """User's selection of an architecture template."""

    selected: str = Field(..., description="Name of the chosen template")
    reason: str = Field(
        ..., description="Why this template was chosen"
    )
    is_user_choice: bool = Field(
        ..., description="True if user chose, False if system decided optimally"
    )


# ── Build Spec ───────────────────────────────────────────────────────────


class SpecPhase(BaseModel):
    """A single phase in the build spec."""

    id: str
    description: str
    deliverables: list[str]
    acceptance_criteria: list[str] = Field(
        default_factory=list, description="Measurable criteria for phase completion"
    )
    estimated_effort: str = Field(
        default="unknown", description="Rough effort estimate (S/M/L/XL)"
    )


class BuildSpec(BaseModel):
    """Structured build spec output for deterministic Coding Agent execution.

    Generated by the full pipeline: Language Game → Disambiguator → Translator
    → Template Selector → Spec Generator.
    """

    id: str = Field(default_factory=lambda: f"spec-{uuid.uuid4().hex[:8]}")
    version: str = Field(default="1.0")
    created_at: str = Field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    language_game: LanguageGame = LanguageGame.GENERAL
    original_prompt: str
    translated_prompt: str  # Proper Technical English
    description: str
    requirements: list[str]
    constraints: list[str] = Field(default_factory=list)
    tech_stack: list[str] = Field(default_factory=list)
    test_strategy: str = Field(
        default="spec-driven", description="tdd or spec-driven"
    )
    architecture: ArchitectureChoice
    phases: list[SpecPhase]
    context_budget_warning: str | None = None  # If spec is too large
    notes: list[str] = Field(default_factory=list)

    @field_serializer("created_at")
    def _serialize_created_at(self, v: str) -> str:
        return v

    @field_serializer("language_game")
    def _serialize_language_game(self, v: LanguageGame) -> str:
        return v.value

    def summary(self) -> str:
        """Return a one-line summary for Trail logging."""
        return (
            f"[{self.id}] {self.description} | arch={self.architecture.selected} "
            f"| phases={len(self.phases)} | reqs={len(self.requirements)}"
        )


class PlannerOutput(BaseModel):
    """Complete output from the Planner/Thinker pipeline.

    Contains the structured spec plus metadata about the translation process.
    """

    spec: BuildSpec
    language_game_detected: LanguageGame
    ambiguities_found: list[Ambiguity] = Field(default_factory=list)
    ambiguities_resolved: list[tuple[Ambiguity, AmbiguityResolution]] = Field(
        default_factory=list
    )
    clarifying_questions_asked: list[ClarifyingQuestion] = Field(default_factory=list)
    templates_presented: list[str] = Field(default_factory=list)
    context_budget_used: int = 0
    context_budget_total: int = 128000

    def summary(self) -> str:
        return f"Planner output: {self.spec.summary()}"
