import { FlatCompat } from "@eslint/eslintrc";
import { dirname } from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      ".next/**",
      "node_modules/**",
      "out/**",
      "playwright-report/**",
      "test-results/**",
      "coverage/**",
      "public/**",
      "next-env.d.ts", // auto-generated by next build; not our code to lint
    ],
  },
  {
    // Node-side config files legitimately use CommonJS require().
    files: ["*.config.js", "jest.config.js", "jest.setup.js", "src/**/__tests__/**/*.{js,ts,tsx}"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
  {
    // Typing-debt rules: keep on but downgrade to warn so CI's --max-warnings
    // knob can still gate on new offenses without failing today. Track the
    // remaining occurrences in docs/history/eslint-debt.md.
    rules: {
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_" },
      ],
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  {
    // Playwright specs frequently use dynamic require() for optional page
    // helpers and node fs. Allow it there without loosening the app rules.
    files: ["tests/**/*.ts", "tests/**/*.tsx", "tests/**/*.spec.ts"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/triple-slash-reference": "off",
    },
  },
];

export default eslintConfig;
