"""Calculator module with add, subtract, multiply, divide.
Generated by S1 Coding Agent
Spec: spec-e2e-001
Phase: spec-e2e-001
"""

from __future__ import annotations
from typing import Union

Number = Union[int, float]


class CalculatorModule:
    """Implementation of calculator operations."""

    def __init__(self) -> None:
        """Initialize calculator."""
        self.history: list[dict[str, Number]] = []

    def add(self, a: Number, b: Number) -> Number:
        """Add two numbers."""
        result = a + b
        self.history.append({"op": "add", "a": a, "b": b, "result": result})
        return result

    def subtract(self, a: Number, b: Number) -> Number:
        """Subtract b from a."""
        result = a - b
        self.history.append({"op": "subtract", "a": a, "b": b, "result": result})
        return result

    def multiply(self, a: Number, b: Number) -> Number:
        """Multiply two numbers."""
        result = a * b
        self.history.append({"op": "multiply", "a": a, "b": b, "result": result})
        return result

    def divide(self, a: Number, b: Number) -> Number:
        """Divide a by b."""
        if b == 0:
            raise ValueError("Cannot divide by zero")
        result = a / b
        self.history.append({"op": "divide", "a": a, "b": b, "result": result})
        return result

    def power(self, base: Number, exponent: Number) -> Number:
        """Raise base to exponent."""
        result = base ** exponent
        self.history.append({"op": "power", "base": base, "exponent": exponent, "result": result})
        return result

    def get_history(self) -> list[dict[str, Number]]:
        """Return operation history."""
        return list(self.history)

    def clear_history(self) -> None:
        """Clear operation history."""
        self.history.clear()

    def execute(self, operation: str, a: Number, b: Number) -> Number:
        """Execute an operation by name."""
        operations = {
            "add": self.add,
            "subtract": self.subtract,
            "multiply": self.multiply,
            "divide": self.divide,
        }
        if operation not in operations:
            raise ValueError(f"Unknown operation: {operation}")
        return operations[operation](a, b)
